### ISSUE TITLE
Loading view item at the end of list

### ISSUE THREAD

**Issue by hilitshenberger** [2307vivek/Paging-3-Sample#3]
I have noticed that when i limit the size of the list (by filtering api) -
@`GET("3/discover/movie?sort_by=vote_count.desc&vote_count.gte=1000&primary_release_year=2000&language=en-US")`
when i get to the end of list - loading view is shown instead of nothing or custom separator (`return@insertSeparators MovieModel.SeparatorItem("End of List !! ")`)
```
if (after == null) {
// we're at the end of the list
// return@insertSeparators //MovieModel.SeparatorItem("End of List !! //")
return@insertSeparators
}
```

**Comment by 2307vivek** [comment]
The issue has been resolved in the latest commit.
The issue was due to the `MoviePagingSource` was loading trying to load the next page even when the last page is reached.

We need to calculate the `nextPage` based on the total pages in `MoviePagingSource`.
```
LoadResult.Page(
    data = movieListResponse.results!!,
    prevKey = if (nextPage == 1) null else nextPage - 1 ,
    nextKey = if (nextPage < movieListResponse.totalPages!!)
        movieListResponse.page?.plus(1) else null
)
```

Now you can show custom separator at the end of the list.
```
if (after == null) {
     // we're at the end of the list
    return@insertSeparators MovieModel.SeparatorItem("End of list")
}
```
